max_width = 80
unstable_features = true

fn_single_line = true
format_macro_matchers = true
format_macro_bodies = true
imports_layout = "Vertical"
merge_imports = true
match_block_trailing_comma = true
force_multiline_blocks = true
normalize_comments = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
format_doc_comments = true
match_arm_blocks = true
overflow_delimited_expr = true
